config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :about, only: [:index]
  resources :work, only: [:index]
  resources :blog, only: [:index]

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end


end

app/controllers/work_controller.rb
class WorkController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="page-header">
  <h1><i class="fa fa-lightbulb-o"></i>at Needham</h1>
</div>

<div class="row">
  <div class="panel">
      <div class="col-xs-12 col-md-8">
        <h2>about me</h2>
      </div>

      <div class="col-xs-6 col-md-4">
        <h2><%= link_to 'back', root_path, id: 'back' %></h2>
      </div>
  </div>
</div>

<div class="row">
  <div class=".col-md-2 col-md-7">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>Professional</h3>
        <p>I am currently enrolled in the Boston General Assembly <%= link_to 'Web Development Immersive', 'https://generalassemb.ly/education/web-development-immersive', target: "_blank" %> (WDI) program to acquire the skills to bring ideas to life.</p>
        <p>I have a background in financial services where I last managed the daily operations of a platform of alternative investments (i.e., hedge funds, private equities, etc.) for high net worth clients.</p>
        <p>I want to take my experience working well under pressure to produce user-friendly results from complex information into the public forum that is the world wide web.</p>
        <p>The WDI ends in early April and I will be excited to bring my new skills to a company within the Greater Boston tech community and have the opportunity to do some contract work until then.</p>
      </div>
    </div>
  </div>

  <div class="col-md-2 col-md-7">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>Personal</h3>
        <p>I grew up in Scarborough, Maine where I enjoyed the beach in the summer and mountains in the winter. </p>
        <p>Having lived in Greater Boston for the past six years, I spend free time with friends, cheering on the Boston sports teams, playing guitar, and otherwise staying in motion.</p>
      </div>
    </div>
  </div>

  <div class="col-md-2 col-md-7">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>contact</h3>

        <p>
          I can be reached easily through any of the following:
        </p>

          <%= link_to 'mailto:patrick.h.needham@gmail.com', target: "_blank" do %>
            <i class="fa fa-envelope-o"></i>
          <% end %>

          <%= link_to 'https://twitter.com/patneedham_', target: "_blank" do %>
            <i class="fa fa-twitter"></i>
          <% end %>

          <%= link_to 'https://www.linkedin.com/in/patrickneedham', target: "_blank" do %>
            <i class="fa fa-linkedin"></i>
          <% end %>

          <%= link_to 'https://www.facebook.com/patrick.h.needham', target: "_blank" do %>
            <i class="fa fa-facebook"></i>
          <% end %>

          <%= link_to 'skype:patrick.h.needham', target: "_blank" do %>
            <i class="fa fa-skype"></i>
          <% end %>

        <p>
          <%= link_to 'https://github.com/goodeats', target: "_blank" do %>
            <i class="fa fa-github"></i>
          <% end %> (my repositories may be a bit crowded at the moment while i'm taking classes)
        </p>

      </div>
    </div>
  </div>
</div>

app/views/blog/index.html.erb
<div class="page-header">
  <h1><i class="fa fa-lightbulb-o"></i>at Needham</h1>
</div>

<div class="row">
  <div class="panel">
      <div class="col-xs-12 col-md-8">
        <h2>blog</h2>
      </div>

      <div class="col-xs-6 col-md-4">
        <h2><%= link_to 'back', root_path, id: 'back' %></h2>
      </div>
  </div>
</div>

<div class="row">
  <div class=".col-md-2 col-md-7">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>up and running</h3>
        <p>I'll be blogging soon as well</p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="page-header">
  <h1><i class="fa fa-lightbulb-o"></i>at Needham<small> welcome!</small></h1>
</div>

<div class="panel">
  <div class="box panel-default">
    <div class="col-xs-12 col-md-8">
      <h2><%= link_to 'about me', about_index_path, id: 'about' %></h2>
    </div>

    <div class="col-xs-12 col-md-8">
      <h2><%= link_to 'my work', work_index_path, id: 'work' %></h2>
    </div>

    <div class="col-xs-12 col-md-8">
      <h2><%= link_to 'blog', blog_index_path, id: 'blog' %></h2>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    This site is under construction. Please visit again soon!
  </div>
</div>

<div index="left-split">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatNeedham</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>


<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/work/index.html.erb
<div class="page-header">
  <h1><i class="fa fa-lightbulb-o"></i>at Needham</h1>
</div>

<div class="row">
  <div class="panel">
      <div class="col-xs-12 col-md-8">
        <h2>my work</h2>
      </div>

      <div class="col-xs-6 col-md-4">
        <h2><%= link_to 'back', root_path, id: 'back' %></h2>
      </div>
  </div>
</div>

<div class="row">
  <div class=".col-md-2 col-md-7">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>just getting started</h3>
        <p>i'll be posting things here soon!</p>
      </div>
    </div>
  </div>
</div>